// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CodeAtlas.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_Snippets : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "CodeAtlas");

            migrationBuilder.CreateTable(
                name: "snippets",
                schema: "CodeAtlas",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    title = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    code = table.Column<string>(type: "text", nullable: false),
                    language = table.Column<int>(type: "integer", nullable: false),
                    visibility = table.Column<int>(type: "integer", nullable: false),
                    is_archived = table.Column<bool>(type: "boolean", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_snippets", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_snippets_created_at_utc",
                schema: "CodeAtlas",
                table: "snippets",
                column: "created_at_utc");

            migrationBuilder.CreateIndex(
                name: "ix_snippets_is_archived",
                schema: "CodeAtlas",
                table: "snippets",
                column: "is_archived");

            migrationBuilder.CreateIndex(
                name: "ix_snippets_language",
                schema: "CodeAtlas",
                table: "snippets",
                column: "language");

            migrationBuilder.CreateIndex(
                name: "ix_snippets_visibility",
                schema: "CodeAtlas",
                table: "snippets",
                column: "visibility");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "snippets",
                schema: "CodeAtlas");
        }
    }
}
