// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CodeAtlas.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_Technologies : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "technologies",
                schema: "CodeAtlas",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    description = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_technologies", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_technologies_name",
                schema: "CodeAtlas",
                table: "technologies",
                column: "name",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "technologies",
                schema: "CodeAtlas");
        }
    }
}
