// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CodeAtlas.Api.Migrations.Application;

/// <inheritdoc />
public partial class Add_SnippetTechnologies : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "snippet_technologies",
            schema: "CodeAtlas",
            columns: table => new
            {
                snippet_id = table.Column<string>(type: "character varying(50)", nullable: false),
                technology_id = table.Column<string>(type: "character varying(50)", nullable: false),
                created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_snippet_technologies", x => new { x.snippet_id, x.technology_id });
                table.ForeignKey(
                    name: "fk_snippet_technologies_snippets_snippet_id",
                    column: x => x.snippet_id,
                    principalSchema: "CodeAtlas",
                    principalTable: "snippets",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
                table.ForeignKey(
                    name: "fk_snippet_technologies_technologies_technology_id",
                    column: x => x.technology_id,
                    principalSchema: "CodeAtlas",
                    principalTable: "technologies",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "ix_snippet_technologies_technology_id",
            schema: "CodeAtlas",
            table: "snippet_technologies",
            column: "technology_id");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "snippet_technologies",
            schema: "CodeAtlas");
    }
}
